name: CI/CD for cypress project

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:  
  build_and_deploy:
    runs-on: windows-10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub pages
        run: |
          # Add your deployment script here
