name : CI/CD for cypress project

on: 
  push:
    branches: 
      - main

jobs:  
  build_and_deploy:
    runs-on: ubantu-latest
    users: action/checkout@v3

    steps:
      name: Checkout repository
      uses: action/checkout@v3