name: CI/CD for Cypress project

on:
  push:
    branches: 
      - main

jobs:  
  build_and_deploy:
    runs-on: windows-10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
